pyproject.toml
8.1.2 does not contain the argument 'use_default_ports_for_scheme' in the source definition of  url_to_node_config.
client_utils.py
=> Updated elastic-transport dependency settings.  

.github/workflows/tests.yml, README.rst, elasticsearch_serverless/_sync/client/utils.py, elasticsearch_serverless/helpers/actions.py, noxfile.py
Raw HTML directives are not supported, and the title underline was wrong.
=> Check package will upload correctly to PyPI

test_elasticsearch_serverless/test_server/test_rest_api_spec.py
The failures are expected and not related to the repository name change.
=> Rename test repository

test_elasticsearch_serverless/test_async/test_server/conftest.py
Applying `pytest.mark.usefixtures` on a pytest fixture does not have any effect, see https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function. The idea was to call `wipe_cluster`, but we do it explicitly now anyways.
Relates https://github.com/elastic/elasticsearch-py/pull/2577
=> Fix pytest warning

test_elasticsearch_serverless/test_async/test_server/test_helpers.py, test_elasticsearch_serverless/test_async/test_server/test_mapbox_vector_tile.py, test_elasticsearch_serverless/test_async/test_server/test_rest_api_spec.py
This is required now that strict mode is the default.
Ports https://github.com/elastic/elasticsearch-py/pull/2276 to serverless.
=> Switch to pytest_asyncio.fixture

test_elasticsearch_serverless/test_async/test_server/test_helpers.py, test_elasticsearch_serverless/test_async/test_server/test_mapbox_vector_tile.py, test_elasticsearch_serverless/test_server/test_helpers.py, test_elasticsearch_serverless/test_server/test_mapbox_vector_tile.py
Using `elasticsearch_url` does not work in serverless as API key authentication is required. Also, `node_class` parametrization does not make sense, we parametrize at the CI job level. And finally, the sync case was missing a refresh.
Depends on https://github.com/elastic/elasticsearch-serverless-python/pull/43
Relates https://github.com/elastic/elasticsearch-py/pull/2580
=> Fix mapbox tests

test_elasticsearch_serverless/test_async/test_server/test_clients.py, test_elasticsearch_serverless/test_server/test_clients.py
There's no guarantee on the number of successful shards, even it it turned out to be predictable outside serverless in practice.
=> Fix test_bulk_works_with_bytestring_body

test_elasticsearch_serverless/test_async/test_server/test_helpers.py, test_elasticsearch_serverless/test_server/test_helpers.py
Using a [join type requires the routing field](https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html) which is apparently forbidden in serverless.
> ERROR test_elasticsearch_serverless/test_server/test_helpers.py::test_children_are_reindexed_correctly - elasticsearch_serverless.exceptions.BadRequestError: BadRequestError(400, 'status_exception', 'Parameter validation failed for [/test-index/_doc/47]: The http parameter [routing] (with value [42]) is not permitted when running in serverless mode')
(Using this feature isn't really recommended anyway.)
=> Remove parent/child tests

test_elasticsearch_serverless/test_async/test_server/test_rest_api_spec.py, test_elasticsearch_serverless/test_server/test_rest_api_spec.py
Here's an example YAML file https://github.com/elastic/elasticsearch-clients-tests/blob/main/tests/ping/ping.yml. The "requires" sections were mistaken for actual tests to run until now.
=> Handle clients-tests requires section

pyproject.toml, test_elasticsearch_serverless/test_async/test_server/test_rest_api_spec.py, test_elasticsearch_serverless/test_server/test_rest_api_spec.py
The benefit of using xfail instead of skip is that if the test starts to pass, we'll be notified.
=> Mark failing tests with pytest.xfail

test_elasticsearch_serverless/test_server/test_helpers.py
It's done correctly in the async test, but not the sync one.
=> Fix refresh in test_reindex_index_datastream

test_elasticsearch_serverless/test_async/test_server/test_helpers.py
I'm not clear why `wait_for` vs. `True` makes a difference, but it worked locally and the sync tests use that. Let's see.
=> Fix timeout

test_elasticsearch_serverless/utils.py
Mainly by not trying to delete system component templates, and deleting everything in one go. Running the tests now takes 9-10mn compare to 30-32mn before.
This can be reviewed commit by commit.
=> Optimize wipe_cluster

elasticsearch_serverless/serializer.py, test_elasticsearch_serverless/test_serializer.py
Backports https://github.com/elastic/elasticsearch-py/pull/2551
=> Remove redundant/deprecated `np.float_` use to fix NumPy 2.0 compat

elasticsearch_serverless/_async/client/__init__.py, elasticsearch_serverless/_async/client/query_rules.py, elasticsearch_serverless/_sync/client/__init__.py, elasticsearch_serverless/_sync/client/query_rules.py, elasticsearch_serverless/client.py
This is based on https://github.com/elastic/elasticsearch-specification/pull/2639 and https://github.com/elastic/elasticsearch-specification/pull/2656. There are some changes, new APIs, and importantly the namespace is now called `query_rules`.
=> Add Query Rules API

test_elasticsearch_serverless/test_server/test_rest_api_spec.py
It timeouts with the async client.
=> Skip inference/10_basic[0]

elasticsearch_serverless/_async/client/indices.py, elasticsearch_serverless/_sync/client/indices.py
The latest changes to commit before the release.
=> Run code generation

.buildkite/generatesteps.py
Unlike https://buildkite.com/elastic/elasticsearch-serverless-python-rest-tests/builds/751 (without the fix), https://buildkite.com/elastic/elasticsearch-serverless-python-rest-tests/builds/752 does not report "unresolved step dependencies".
This was causing projects to not be terminated. And then we reached 100 projects in QA, and projects could not even start.
=> Fix teardown of projects in CI

docs/guide/release-notes.asciidoc, elasticsearch_serverless/_version.py, pyproject.toml, test_elasticsearch_serverless/utils.py
=> Release 0.3.0.20231031

docs/sphinx/api.rst, elasticsearch_serverless/_async/client/__init__.py, elasticsearch_serverless/_async/client/connector.py, elasticsearch_serverless/_sync/client/__init__.py, elasticsearch_serverless/_sync/client/connector.py, elasticsearch_serverless/client.py
Backports https://github.com/elastic/elasticsearch-py/pull/2621
=> Add Connector API

elasticsearch_serverless/_async/client/__init__.py, elasticsearch_serverless/_async/client/cat.py, elasticsearch_serverless/_async/client/cluster.py, elasticsearch_serverless/_async/client/esql.py, elasticsearch_serverless/_async/client/indices.py, elasticsearch_serverless/_async/client/ingest.py, elasticsearch_serverless/_async/client/ml.py, elasticsearch_serverless/_async/client/query_rules.py, elasticsearch_serverless/_async/client/search_application.py, elasticsearch_serverless/_async/client/sql.py, elasticsearch_serverless/_async/client/synonyms.py, elasticsearch_serverless/_sync/client/__init__.py, elasticsearch_serverless/_sync/client/cat.py, elasticsearch_serverless/_sync/client/cluster.py, elasticsearch_serverless/_sync/client/esql.py, elasticsearch_serverless/_sync/client/indices.py, elasticsearch_serverless/_sync/client/ingest.py, elasticsearch_serverless/_sync/client/ml.py, elasticsearch_serverless/_sync/client/query_rules.py, elasticsearch_serverless/_sync/client/search_application.py, elasticsearch_serverless/_sync/client/sql.py, elasticsearch_serverless/_sync/client/synonyms.py
* Remove Get data stream stats API
* Add `include_named_queries_score` to Search and Multi Search API
* Add `q` to Update by Query API
* Add `index_filter` to Open point in time API
* Add `timeout`, `master_timeout` and `verbose` to various APIs
* Add `allow_no_indices` and `ignore_unavailable` to Resolve index API
* Add `deprecated` to Put pipeline API
=> Auto-generated code for main

utils/build-dists.py
While trying to automate the release of 0.4.0 I noticed that the build-dists.py script is out of date, as it was not updated when the package changed from setup.py to pyproject.toml.
This PR has some changes and simplifications that enabled me to do the release. Open to discuss if we can simplify it even more.
=> Updated build-dists.py to work with pyproject.toml

docs/guide/configuration.asciidoc, elasticsearch_serverless/__init__.py, elasticsearch_serverless/serializer.py, noxfile.py, pyproject.toml, test_elasticsearch_serverless/test_serializer.py
This is nice in its own right, but also a prerequisite for Arrow support.
Backports https://github.com/elastic/elasticsearch-py/pull/2493 and https://github.com/elastic/elasticsearch-py/pull/2508
=> Add optional orjson support

elasticsearch_serverless/_otel.py, elasticsearch_serverless/helpers/actions.py, test_elasticsearch_serverless/test_otel.py, test_elasticsearch_serverless/test_server/test_helpers.py, test_elasticsearch_serverless/test_server/test_otel.py
Backports the following:
* https://github.com/elastic/elasticsearch-py/pull/2616
* https://github.com/elastic/elasticsearch-py/pull/2654
Tested using a Serverless cluster but sending data to a Hosted cluster. Only the parallel bulk spans are expanded here, for visibility:
=> Fix OTel context loss in bulk helpers

docs/guide/release-notes.asciidoc, elasticsearch_serverless/_version.py, pyproject.toml
I have a fix for the failure in https://github.com/elastic/elasticsearch-clients-tests/pull/145. I think this should not block the release.
=> Release 0.5.0

catalog-info.yaml
Every 12 hours is too much, especially when they are failing! Also, let's use 2AM UTC to avoid running tests at midnight UTC, which is often busy.
=> Run tests only once per day

elasticsearch_serverless/_otel.py, noxfile.py
Right now, `utils/build-dists.py` calls mypy with opentelemetry-api installed, which was failing. This change reduces the diff, but I'm wondering if `utils/build-dists.py` should not use `nox -s lint` instead.
=> Type check against opentelemetry-api

test_elasticsearch_serverless/utils.py
They are currently breaking CI: https://buildkite.com/elastic/elasticsearch-serverless-python-rest-tests/builds/1217#01946cd9-a079-430a-b838-8a0222f21c52
=> Ignore more serverless index templates
